apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ochestra-ai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ochestra-ai
subjects:
- kind: ServiceAccount
  name: ochestra-ai
  namespace: monitoring